// react-version/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <div style={{width: "100%", height: "20rem", "text-align": "left", padding: "10px"}}>
          <my-component first="Stencil" last="'Don't call me a framework' JS"></my-component>
        </div>
      </div>
    );
  }

}

export default App;

// vue-version/src/App.vue
<template>
  <div id="app">
    <img src="./assets/logo.png">
    <div style="width: 100%; height: 20rem; text-align: left;">
      <my-component first="Stencil" last="'Don't call me a framework' JS"></my-component>
    </div>
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>

<script>
import HelloWorld from './components/HelloWorld.vue'

export default {
  name: 'app',
  components: {
    HelloWorld
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
