// react-version/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import { wc } from './utils/webcomponent';

class App extends Component {

  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <div style={{width: "100%", height: "20rem", "textAlign": "left", padding: "10px"}}>
          <my-component 
            first="Stencil" 
            last="'Don't call me a framework' JS"
            ref={wc({
              onEvent: (e) => this.eventInReact(e)
            })}>
          </my-component>
        </div>
      </div>
    );
  }

  eventInReact = ($event) => {
    console.log($event);
  }
}

export default App;

// angular-version/src/app/app.component.ts
import { Component, ViewChild, ElementRef, Renderer2 } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';

  eventInAngular($event: Event) {
    console.log($event);
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>

<div style="width: 100%; height: 20rem; text-align: left;">
  <my-component 
    first="Stencil" 
    last="'Don't call me a framework' JS"
    (onEvent)="eventInAngular($event)">
  </my-component>
</div>

<h1>
  Welcome to {{ title }}!
</h1>

<h2>Here are some links to help you start: </h2>
<ul>
  <li>
    <h2><a target="_blank" rel="noopener" href="https://angular.io/tutorial">Tour of Heroes</a></h2>
  </li>
  <li>
    <h2><a target="_blank" rel="noopener" href="https://github.com/angular/angular-cli/wiki">CLI Documentation</a></h2>
  </li>
  <li>
    <h2><a target="_blank" rel="noopener" href="https://blog.angular.io/">Angular blog</a></h2>
  </li>
</ul>
